In [2]:
L = [2345, 54, 86478, 697, 782, -8452]
L

[2345, 54, 86478, 697, 782, -8452]

In [3]:
import numpy as np

In [4]:
np.array(L)

array([ 2345,    54, 86478,   697,   782, -8452])

In [5]:
a = np.array(L)
a

array([ 2345,    54, 86478,   697,   782, -8452])

In [6]:
a.mean()

13650.666666666666

---


In [8]:
a

array([ 2345,    54, 86478,   697,   782, -8452])

In [7]:
#slicing de arrays
a[1:3]

array([   54, 86478])

In [10]:
ab= a.copy() #copia de un array
ab

array([ 2345,    54, 86478,   697,   782, -8452])